
# base image dsdsdfsfdf sdsds
FROM postgres:11.1-alpine
#This old version works, not sure how to upgrade to newest version
#FROM postgres:10.7-alpine

# run create.sql on init
ADD create.sql /docker-entrypoint-initdb.d